import { Inter } from "next/font/google";
import "./globals.css";
import TopNav from "../components/TopNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <TopNav />
      {/* <h1>this is the navbar</h1> */}
      {children}
      </body>
    </html>
  );
}
